# Generated by Django 3.2.7 on 2022-01-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20220102_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='板块名称')),
                ('msg', models.TextField(default='版主没有留下任何信息', verbose_name='简介')),
                ('is_avtive', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('count_title', models.IntegerField(default=0, verbose_name='主题数')),
                ('plate_root_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='create_plate', to='user.user')),
            ],
        ),
    ]
