# Generated by Django 3.2.7 on 2022-01-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_sex'),
        ('plate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='save_user',
            field=models.ManyToManyField(related_name='save_plate', to='user.User'),
        ),
    ]
