# Generated by Django 3.2.7 on 2022-01-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20220102_1654'),
        ('plate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='plate.plate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_article', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='msg.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='user.user')),
            ],
        ),
    ]
