# Generated by Django 3.2.7 on 2022-01-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_article_save_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count_comment',
            field=models.IntegerField(default=0, verbose_name='热度'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_good',
            field=models.BooleanField(default=False, verbose_name='精选'),
        ),
    ]
