# Generated by Django 3.2.7 on 2021-12-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='账号')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('birthday', models.DateTimeField(verbose_name='生日')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
