# Generated by Django 3.2.7 on 2022-01-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='U_func',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='等级')),
                ('exp', models.IntegerField(default=0, verbose_name='经验值')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='uname',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '女性'), (1, '男性')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default='1999-1-1', verbose_name='生日'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_user', to='user.user')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to='user.user')),
            ],
        ),
    ]
