# Generated by Django 3.2.7 on 2022-01-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220102_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '女性'), (1, '男性')], default=1, verbose_name='性别'),
        ),
    ]
