# Generated by Django 3.2.7 on 2022-01-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220102_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='U_func',
        ),
        migrations.AddField(
            model_name='user',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='经验值'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, verbose_name='等级'),
        ),
    ]
